{"name": "test_16_form_authentication_wrong_username", "status": "passed", "steps": [{"name": "Открытие главной страницы сайта", "status": "passed", "start": 1664801038817, "stop": 1664801040823}, {"name": "Открытие страницы с примером Form Authentication", "status": "passed", "start": 1664801040823, "stop": 1664801041410}, {"name": "Заполнение формы username с ошибкой", "status": "passed", "start": 1664801041410, "stop": 1664801041501}, {"name": "Заполнение формы password", "status": "passed", "start": 1664801041501, "stop": 1664801041591}, {"name": "Нажатие кнопки Login", "status": "passed", "start": 1664801041591, "stop": 1664801042004}], "attachments": [{"name": "stdout", "source": "9fd4f3d1-6b19-46c8-91b9-0c780f4cd002-attachment.txt", "type": "text/plain"}], "start": 1664801038817, "stop": 1664801042029, "uuid": "470200b4-8238-42f9-a32d-0226f6d4cada", "historyId": "37640a2f2509219f0a4370bd364b1981", "testCaseId": "3bf9f3b198762f4f5e6cd2b95e8ca890", "fullName": "pom.tests.test_diplom#test_16_form_authentication_wrong_username", "labels": [{"name": "feature", "value": "Проверка авторизации c ошибкой в username"}, {"name": "suite", "value": "Авторизации с ошибкой в username"}, {"name": "tag", "value": "@pytest.mark.usefixtures('text_inside_test')"}, {"name": "parentSuite", "value": "pom.tests"}, {"name": "host", "value": "DESKTOP-I5N6LU0"}, {"name": "thread", "value": "53864-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "pom.tests.test_diplom"}]}